name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features

  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04, macos-12, windows-latest]

    steps:
    - uses: actions/checkout@v3

# TODO: Actually build with this: https://blog.logrocket.com/guide-cross-compilation-rust/
#    - if: ${{ matrix.os == 'windows-latest' }}
#      run: rustup target add aarch64-pc-windows-msvc
#    - if: ${{ matrix.os == 'macos-12' }}
#      run: rustup target add aarch64-apple-darwin
#    - if: ${{ matrix.os == 'ubuntu-20.04' }}
#      run: |
#        rustup target add aarch64-unknown-linux-gnu
#        rustup target add arm-unknown-linux-gnueabihf

    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --verbose --release
    - name: Run tests
      run: cargo test --verbose
    - name: Upload binaries
      uses: actions/upload-artifact@v3
      if: ${{ success() }}
      with:
        name: octynectl-${{ matrix.os }}
        path: target/release/octynectl${{ matrix.os == 'windows-latest' && '.exe' || '' }}
    # TODO: rustfmt check?
